### YamlMime:FAQ
metadata:
  title: 질문과 대답
  description: HoloLens 혼합 현실 디바이스에 대해 자주 묻는 보안 질문과 대답을 최신 상태로 유지합니다.
  ms.assetid: bd55ecd1-697a-4b09-8274-48d1499fcb0b
  author: pawinfie
  ms.author: pawinfie
  ms.date: 02/19/2020
  keywords: hololens, Windows Mixed Reality, security
  ms.prod: hololens
  ms.sitesec: library
  ms.topic: article
  audience: ITPro
  ms.localizationpriority: medium
  ms.custom:
  - CI 111456
  - CSSTroubleshooting
  manager: bradke
  ms.openlocfilehash: b09670ee24139c129629d061edae4d5bb43b2d766c90df152aeddb202cc1fe55
  ms.sourcegitcommit: f8e7cc2fbdcdf8962700fd50b9c017bd83d1ad65
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 08/05/2021
  ms.locfileid: "115662656"
title: 자주 묻는 HoloLens(1세대) 보안 질문
summary: ''
sections:
- name: 무시됨
  questions:
  - question: >
      HoloLens 1은 어떤 수준의 데이터 보호를 제공하나요?
    answer: >
      * [HoloLens(1세대) BitLocker 암호화를](hololens1-encryption.md) 참조하세요.
  - question: >
      어떤 유형의 무선이 사용됩니까?
    answer: >
      * 802.11ac 및 Bluetooth 4.1 LE
  - question: >
      통합되는 아키텍처 유형은 무엇인가요?  예: 가리킨 점, 메시 또는 다른 것은 무엇인가요?
    answer: >
      * Wi-Fi 인프라 모드에서 다른 무선 액세스 지점과 통신하는 데 사용할 수 있습니다.

      * Bluetooth 사용하여 고객의 애플리케이션에서 지원하는 경우 여러 HoloLens 피어 간 또는 다른 Bluetooth 디바이스와 피어 간을 대화할 수 있습니다.
  - question: >
      미국 3대 ID란?
    answer: >
      * C3K1688
  - question: >
      디바이스가 작동하는 빈도 범위 및 채널은 무엇이며 구성할 수 있나요?
    answer: >
      * Wi-Fi: 빈도 범위는 사용자가 구성할 수 없으며 사용 국가에 따라 달라집니다. 미국 Wi-Fi 2.4GHz(1-11) 채널과 5GHz(36-64, 100-165) 채널을 모두 사용합니다.

      * Bluetooth: Bluetooth 표준 2.4-2.48GHz 범위를 사용합니다.
  - question: >
      디바이스에서 특정 빈도를 허용하거나 차단할 수 있나요?
    answer: >
      * 이는 사용자/디바이스에서 제어할 수 없습니다.
  - question: >
      전송 및 수신의 전원 수준은 무엇인가요? 조정할 수 있나요? 작업 범위는 무엇인가요?
    answer: >
      * 배출 테스트 표준은 [여기에서](https://fccid.io/C3K1688)찾을 수 있습니다. 작업 범위는 액세스 지점 및 환경에 따라 크게 달라지지만 다른 고품질 휴대폰, 태블릿 또는 PC와 거의 동일합니다.
  - question: >
      정상 작동의 업무 주기/수명은 무엇인가요?
    answer: >
      * 활성 사용 2-3시간 및 최대 2주 대기 시간

      * 배터리 수명을 사용할 수 없습니다.
  - question: >
      도구가 범위에 없는 경우 전송 및 수신 동작은 무엇인가요?
    answer: >
      * HoloLens 전송/수신은 표준 Wi-Fi/Bluetooth 패턴을 따릅니다. 범위의 가장자리에서 완전히 연결이 끊어질 때까지 입력이 끊기는 것을 알 수 있지만, 범위로 돌아가면 신속하게 다시 연결해야 합니다.
  - question: >
      제곱 피트당 배포 밀도란?
    answer: >
      * 이는 네트워크 인프라에 따라 달라집니다.
  - question: >
      디바이스에서 인프라를 클라이언트로 사용할 수 있나요?
    answer: >
      * Yes
  - question: >
      어떤 프로토콜이 사용됩니까?
    answer: >
      * HoloLens 독점 프로토콜을 사용하지 않습니다.
  - question: >
      OS 업데이트 빈도 – HL에 대한 OS 업데이트 빈도는 어떻게 됩니까?  일정이 설정되어 있나요?  Microsoft는 필요에 따라 보안 패치를 릴리스하나요?
    answer: >
      * Microsoft는 Windows 10 대해 수행된 것과 정확히 동일한 방식으로 HoloLens OS 업데이트를 제공합니다. 일반적으로 연간 두 가지 주요 업데이트가 있으며, 하나는 봄이고, 다른 하나는 봄입니다. HoloLens Windows 디바이스이기 때문에 업데이트 개념은 다른 Windows 디바이스와 동일합니다. Microsoft는 필요에 따라 보안 패치를 릴리스하고 다른 Windows 디바이스에서 수행한 것과 동일한 개념을 따릅니다.
  - question: >
      OS 강화 – OS를 강화하기 위한 옵션은 무엇인가요?  불필요한 앱 또는 서비스를 제거하거나 종료할 수 있나요?
    answer: >
      * HoloLens 스마트폰처럼 동작합니다. 다른 최신 Windows 디바이스와 비슷합니다. HoloLens Microsoft Intune 또는 MobileIron, Airwatch 또는 Soti와 같은 다른 최신 장치 관리 솔루션에서 관리될 수 있습니다. 이러한 관리 시스템에는 디바이스에 보안 정책을 배치하고 디바이스를 강화하기 위해 설정할 수 있는 정책이 있습니다. 필요한 경우 불필요한 애플리케이션을 삭제하는 옵션도 있습니다.
  - question: >
      소프트웨어 애플리케이션은 어떻게 관리 및 업데이트하나요? Microsoft Store에 있는 앱에 대해 로드되는 앱 및 앱 업데이트 프로세스를 정의해야 하는 제어는 무엇인가요?
    answer: >
      * HoloLens Windows 저장소를 통해서만 소프트웨어 애플리케이션을 가져옵니다. HoloLens 사용을 위해 개발된 Appx 애플리케이션 패키지만 설치할 수 있습니다. Microsoft Store HoloLens 디바이스를 보여 주는 애플리케이션 옆에 약간의 로고를 사용하여 이를 확인할 수 있습니다. 스토어 애플리케이션 관리에 대한 모든 제어는 HoloLens 적용됩니다. 공식 매장 또는 비즈니스용 스토어의 개념을 사용할 수 있습니다. 앱은 사이드로드되거나(Windows 디바이스에서 앱을 로드하는 수동 프로세스) 필요할 때 스토어에서 앱을 자동으로 끌어오도록 MDM을 통해 관리될 수 있습니다.
  - question: >
      HoloLens 스토어의 앱 업데이트 빈도는 어떻게 됩니까?
    answer: >
      * Microsoft Store 동일한 개념을 따르고 앱을 끌어오면 애플리케이션 개발자가 업데이트 주기를 결정합니다. 저장소에서 업데이트 메커니즘을 제어해야 하는 모든 관리 옵션은 HoloLens 적용됩니다.
  - question: >
      HoloLens 보안 부팅 기능이 있나요?
    answer: >
      * Yes
  - question: >
      디바이스에서 주변 장치 지원을 사용하지 않도록 설정하거나 연결을 끊을 수 있나요?
    answer: >
      * Yes
  - question: >
      디바이스에서 포트 사용을 제어하거나 사용하지 않도록 설정하는 기능이 있나요?
    answer: >
      * HoloLens 두 개의 포트만 포함됩니다(하나는 헤드셋용이고 다른 하나는 충전용이거나 PC에 연결). 기능 및 복구 이유로 인해 포트를 사용하지 않도록 설정할 수 없습니다.
  - question: >
      바이러스 백신, 엔드포인트 검색, IPS, 앱 제어 허용 목록 – 바이러스 백신, 엔드포인트 검색, IPS, 앱 제어 허용 목록 등을 실행하는 모든 기능
    answer: >
      * Windows Holographic for Business(상업용 제품군)는 Windows Defender Smart Screen을 지원합니다. 바이러스 백신 회사가 앱을 만들어 유니버설 Windows 플랫폼에 게시하는 경우 HoloLens 다운로드할 수 있습니다. 현재 HoloLens 대해 이 작업을 수행한 회사는 없습니다.

      * Microsoft Enterprise Store를 사용하여 앱을 허용할 수 있습니다. 여기서 다운로드할 수 있는 특정 앱만 선택할 수 있습니다. 또한 MDM을 통해 디바이스에서 실행하거나 볼 수 있는 특정 앱을 잠글 수 있습니다.
  - question: >
      디바이스가 오랫동안 오프라인인 경우 디바이스를 업데이트할 때까지 prod 네트워크에서 디바이스를 격리할 수 있나요?  예: 디바이스가 6개월 동안 전원이 켜지지 않은 서랍에 있으며 업데이트, 패치 등을 받지 못했습니다.  네트워크에 연결하려고 할 때 플래그를 지정하고 네트워크에 가입하기 위해 불만 사항 전에 다른 네트워크에서 업데이트해야 한다고 말할 수 있습니다.
    answer: >
      * 이는 MDM 또는 온-프레임 서버에서 인프라 수준에서 관리될 수 있는 것입니다. 지정된 업데이트 버전을 충족하지 않는 디바이스는 비준수로 플래그가 지정될 수 있습니다.
  - question: >
      Microsoft에서 화면 공유 또는 원격 지원을 위해 디바이스에 연결할 수 있는 백도어 또는 서비스에 대한 액세스 권한이 Microsoft에 포함되어 있나요?
    answer: >
      * No
  - question: >
      신뢰할 수 있는 통신을 위해 PKI 인증서를 생성할 때 해당 디바이스에만 있고, 해당 디바이스에 고유하며, 디바이스를 내보내거나 가장하는 데 사용할 수 없도록 디바이스에서 인증서를 생성하려고 합니다. HoloLens 맞나요? 그렇지 않은 경우 잠재적인 완화 방법이 있나요?
    answer: >-
      * SCEP용 CSR은 디바이스 자체에서 생성됩니다. Intune 및 온-프레미스 SCEP 커넥터는 클라이언트에 전송된 챌린지 문자열을 추가하고 확인하여 요청 자체를 보호하는 데 도움이 될 수 있습니다.

      * HoloLens(1세대 및 2세대)에는 TPM 모듈이 있기 때문에 이러한 인증서는 TPM 모듈에 저장되며 추출할 수 없습니다. 또한 추출할 수 있더라도 다른 디바이스에서 챌린지 문자열을 확인할 수 없어 인증서/키를 다른 디바이스에서 사용할 수 없게 렌더링합니다.
