### YamlMime:FAQ
metadata:
  title: 질문과 대답
  description: HoloLens 혼합 현실 장치에 대 한 일반적인 보안 질문과 답변을 최신 상태로 유지 합니다.
  ms.assetid: bd55ecd1-697a-4b09-8274-48d1499fcb0b
  author: pawinfie
  ms.author: pawinfie
  ms.date: 02/19/2020
  keywords: hololens, Windows Mixed Reality, security
  ms.prod: hololens
  ms.sitesec: library
  ms.topic: article
  audience: ITPro
  ms.localizationpriority: medium
  ms.custom:
  - CI 111456
  - CSSTroubleshooting
  manager: bradke
  ms.openlocfilehash: 108f2e4c0aa9af251ecb6bc5185c7803ae51b5f7
  ms.sourcegitcommit: c43cd2f450b643ad4fc8e749235d03ec5aa3ffcf
  ms.translationtype: MT
  ms.contentlocale: ko-KR
  ms.lasthandoff: 07/12/2021
  ms.locfileid: "113637280"
title: 자주 묻는 HoloLens(1세대) 보안 질문
summary: ''
sections:
- name: 무시됨
  questions:
  - question: >
      1 개 제품 HoloLens 하는 데이터 보호 수준
    answer: >
      * [HoloLens (첫 번째 Gen) BitLocker 암호화를](hololens1-encryption.md) 참조 하세요.
  - question: >
      어떤 종류의 무선을 사용 하나요?
    answer: >
      * 802.11 ac 및 Bluetooth 4.1 LE
  - question: >
      어떤 형식의 아키텍처가 통합 되나요?  예: point to point, 메시 또는 기타 항목
    answer: >
      * Wi-Fi는 인프라 모드에서 다른 무선 액세스 지점과 통신 하는 데 사용할 수 있습니다.

      * Bluetooth를 사용 하 여 고객의 응용 프로그램이이를 지원 하거나 다른 Bluetooth 장치를 지 원하는 경우 여러 HoloLens 간에 피어 투 피어를 통신할 수 있습니다.
  - question: >
      FCC ID 란?
    answer: >
      * C3K1688
  - question: >
      장치가 작동 하는 빈도 범위와 채널은 무엇 이며 구성할 수 있나요?
    answer: >
      * Wi-fi: 빈도 범위는 사용자가 구성할 수 없으며 사용 국가에 따라 다릅니다. 미국 Wi-Fi 2.4 GHz (1-11) 채널과 GHz (36-64, 100-165) 채널을 모두 사용 합니다.

      * Bluetooth: Bluetooth 표준 2.4-2.48 GHz 범위를 사용 합니다.
  - question: >
      장치에서 특정 주파수를 허용 하거나 차단할 수 있나요?
    answer: >
      * 사용자/장치에서 제어할 수 없습니다.
  - question: >
      전송 및 수신의 전원 수준은 무엇 인가요? 조정할 수 있나요? 작업 범위는 어떻습니까?
    answer: >
      * 이러한 방출 테스트 표준은 [여기](https://fccid.io/C3K1688)에서 찾을 수 있습니다. 작업 범위는 액세스 지점 및 환경에 따라 크게 달라 지지만 다른 고품질 전화, 태블릿 또는 Pc와 거의 동일 합니다.
  - question: >
      정상 작동에 대 한 업무 주기/수명
    answer: >
      * 2-3 시간 동안 활성 사용 시간 및 최대 2 주 (대기 시간)

      * 배터리 수명을 사용할 수 없습니다.
  - question: >
      도구가 범위 내에 있지 않으면 전송 및 수신 동작 이란?
    answer: >
      * HoloLens 전송/수신은 표준 wi-fi/Bluetooth 패턴을 따릅니다. 범위에서의 가장자리에는 완전히 연결이 끊어질 때까지 입력이 고르지 않을 수 있지만, 범위를 다시 연결한 후에는 신속 하 게 다시 연결 해야 합니다.
  - question: >
      평방 피트 당 배포 밀도 란?
    answer: >
      * 이는 네트워크 인프라에 따라 달라 집니다.
  - question: >
      장치에서 인프라를 클라이언트로 사용할 수 있나요?
    answer: >
      * 예
  - question: >
      사용 되는 프로토콜은 무엇 인가요?
    answer: >
      * HoloLens는 소유 프로토콜을 사용 하지 않습니다.
  - question: >
      OS 업데이트 빈도 – HL에 대 한 OS 업데이트의 빈도는 어떻습니까?  설정 일정이 있나요?  Microsoft는 필요에 따라 보안 패치를 출시 합니다.
    answer: >
      * Microsoft는 Windows 10에 대해 수행 되는 것과 동일한 방식으로 HoloLens에 대 한 OS 업데이트를 제공 합니다. 일반적으로 두 가지 주요 업데이트 (스프링의 경우 1 개)는 한 가지입니다. HoloLens Windows 장치 이므로 업데이트 개념은 다른 Windows 장치와 동일 합니다. Microsoft는 필요에 따라 보안 패치를 해제 하 고 다른 Windows 장치에서 수행 하는 것과 동일한 개념을 따릅니다.
  - question: >
      OS 강화 – OS를 강화 하기 위한 옵션은 무엇 인가요?  불필요 한 앱 또는 서비스를 제거 하거나 종료할 수 있나요?
    answer: >
      * HoloLens은 스마트폰 처럼 동작 합니다. 다른 최신 Windows 장치와 비교할 수 있습니다. HoloLens은 Microsoft Intune 또는 기타 최신 장치 관리 솔루션 (예: MobileIron,, 영화 감시 또는 soti)을 통해 관리할 수 있습니다. 장치에 보안 정책을 추가 하 고 장치를 강화 하기 위해 이러한 관리 시스템에서 설정할 수 있는 정책이 있습니다. 원하는 경우 불필요 한 응용 프로그램을 삭제 하는 옵션도 있습니다.
  - question: >
      소프트웨어 응용 프로그램을 어떻게 관리 하 고 업데이트 하나요? Microsoft store에 포함 된 앱에 대해 로드 된 앱과 앱 업데이트 프로세스를 정의 하는 데 필요한 제어는 무엇 인가요?
    answer: >
      * HoloLens Windows 저장소를 통해서만 소프트웨어 응용 프로그램을 가져옵니다. HoloLens 사용을 위해 개발 된 Appx 응용 프로그램 패키지만 설치할 수 있습니다. Microsoft Store에서 HoloLens 장치를 표시 하는 응용 프로그램 옆의 작은 로고를 사용 하 여이를 확인할 수 있습니다. 스토어 응용 프로그램 관리에 대 한 모든 컨트롤은 HoloLens에도 적용 됩니다. 공식 스토어 또는 비즈니스용 스토어의 개념을 사용할 수 있습니다. 앱은 테스트용으로 로드 (Windows 장치에서 앱을 로드 하는 수동 프로세스) 하거나, 필요할 때 앱을 자동으로 스토어에서 끌어올 수 있도록 MDM을 통해 관리할 수 있습니다.
  - question: >
      HoloLens 스토어에서 앱 업데이트의 빈도는 어떻게 되나요?
    answer: >
      * Microsoft Store와 동일한 개념을 따르고 여기에서 앱을 가져올 때 업데이트 주기는 응용 프로그램 개발자에 의해 결정 됩니다. 저장소에서 업데이트 메커니즘을 제어 해야 하는 모든 관리 옵션은 HoloLens에도 적용 됩니다.
  - question: >
      HoloLens에 대 한 보안 부팅 기능이 있나요?
    answer: >
      * 예
  - question: >
      장치에서 주변 장치 지원을 사용 하지 않도록 설정 하거나 연결을 끊는 기능이 있나요?
    answer: >
      * 예
  - question: >
      장치에서 포트 사용을 제어 하거나 사용 하지 않도록 설정할 수 있나요?
    answer: >
      * HoloLens에는 두 개의 포트 (헤드폰 용 1 개와 pc에 대 한 충전 또는 pc 연결)만 포함 되어 있습니다. 기능 및 복구 이유로 인해 포트를 사용 하지 않도록 설정할 수 없습니다.
  - question: >
      바이러스 백신, 끝점 검색, IP, 앱 컨트롤 허용 목록 – 바이러스 백신, 끝점 검색, IP, 앱 제어 허용 목록 등을 실행 하는 모든 기능
    answer: >
      * Windows Holographic for Business (상업용 제품군) Windows Defender 스마트 화면을 지원 합니다. 바이러스 백신 회사에서 앱을 만들어 유니버설 Windows 플랫폼에 게시 하는 경우 HoloLens에서 다운로드할 수 있습니다. 현재는 HoloLens에 대해 회사에서이 작업을 수행 하지 않았습니다.

      * 앱 허용은 Microsoft Enterprise 저장소를 사용 하 여 다운로드할 수 있는 특정 앱만 선택할 수 있습니다. 또한 MDM을 통해 장치에서 어떤 특정 앱을 실행 하거나 볼 수 있는지를 잠글 수 있습니다.
  - question: >
      장치가 오랫동안 오프 라인 상태 이면 장치를 업데이트할 때까지 prod 네트워크에서 장치를 격리할 수 있나요?  예: 장치가 특정 기간 (6 개월) 동안 전원이 켜지 지 않고 업데이트, 패치 등을 받지 않은 서랍에 앉아 있습니다.  네트워크에 연결 하려고 할 때이에 플래그를 지정 하 고 네트워크에 연결 하기 위해 불만을 발생 시키기 전에 다른 네트워크에서 업데이트 해야 한다고 말할 수 있습니다.
    answer: >
      * 이는 인프라 수준에서 MDM 또는 온-프레미스 서버에 의해 관리 될 수 있는 항목입니다. 지정 된 업데이트 버전을 충족 하지 않는 장치는 호환 되지 않는 것으로 플래그가 지정 될 수 있습니다.
  - question: >
      Microsoft에서 화면 공유 또는 원격 지원을 위해 Microsoft가 장치에 연결할 수 있도록 하는 모든 후방 문이나 서비스에 대 한 액세스를 포함 합니까?
    answer: >
      * 아니요
  - question: >
      신뢰할 수 있는 통신을 위해 PKI 인증서를 생성 하는 경우 장치에서 인증서를 생성 하 여 해당 장치에만 있고 장치를 가장 하는 데 사용 하거나 내보낼 수 없습니다. HoloLens에서이 작업을 하는 경우 잠재적인 완화가 없으면
    answer: >-
      * SCEP 용 CSR은 장치 자체에서 생성 됩니다. Intune 및 온-프레미스 SCEP 커넥터는 클라이언트에 전송 되는 챌린지 문자열을 추가 하 고 확인 하 여 요청 자체의 보안을 유지 합니다.

      * HoloLens (1 세대 및 2 세대)에는 tpm 모듈이 있으므로 이러한 인증서는 tpm 모듈에 저장 되며 추출할 수 없습니다. 또한 추출할 수 있는 경우에도 다른 장치에서 챌린지 문자열을 확인할 수 없으며, 다른 장치에서 인증서/키를 사용할 수 없습니다.
